# Generated by Django 3.0.6 on 2020-06-01 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('jumlah', models.IntegerField()),
                ('tanggal_antar', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Dalam Proses', 'Dalam Proses'), ('Selesai', 'Selesai'), ('Kosong', 'Kosong')], default='Kosong', max_length=20)),
            ],
        ),
    ]
