# Generated by Django 3.0.6 on 2020-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anak',
            name='jumlah',
            field=models.IntegerField(default=0),
        ),
    ]
