# Generated by Django 3.0.6 on 2020-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200606_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='anak',
            name='image_profile',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
