# Generated by Django 3.0.6 on 2020-06-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_anak_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anak',
            name='image_profile',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
